variable "VPC_CIDR" {}
variable "PROJECT" {}
variable "ENV" {}
variable "PRIVATE_SUBNETS_CIDR" {}
variable "PUBLIC_SUBNETS_CIDR" {}
variable "AZ" {}
variable "DEFAULT_VPC_ID" {}
variable "DEFAULT_VPC_CIDR" {}
variable "DEFAULT_VPC_RT" {}
variable "PRIVATE_ZONE_ID" {}
variable "PUBLIC_ZONE_ID" {}
